### ISSUE TITLE
areas example uses imports that are not available

### ISSUE THREAD

**Issue by Anton-4** [StephanvanSchaik/mmap-rs#1]
Trying to use the imports shown in the areas example:
```rust
use mmap_rs::{Error, MemoryMaps, Protection, ShareMode};
```
Shows errors for all imports:
- enum `Error` is private
- unresolved imports: `mmap_rs::MemoryMaps`, `mmap_rs::Protection`, `mmap_rs::ShareMode`

**Comment by StephanvanSchaik** [comment]
It sounds like you are trying to use the 0.3 release that is available on crates.io. The areas example is part of the upcoming 0.4 release, and currently only runs if you specify the crate as:

```
mmap-rs = { git = "https://github.com/StephanvanSchaik/mmap-rs" }
```

Unfortunately, there are a few things that are left to do for me before I am publishing 0.4, but I will try to have a look at that this week.

**Comment by Anton-4** [comment]
Oh right, that makes sense, thanks for the tip! No need to rush :)
